### ISSUE TITLE
Errors happening on Vertx Running the tests

### ISSUE THREAD

**Issue by luistduarte** [reTHINK-project/dev-msg-node-vertx#25]
After this commit ( https://github.com/reTHINK-project/dev-msg-node-vertx/commit/d6c185fe5710a2e3557fe512b11454f3be8cd1ae ) to master branch this error appear..

```
RESOURCE-OPEN
[Policies-Connector][Received]: {"id":1,"type":"open","from":"runtime:/alice1","to":"mn:/session"}
Oct 03, 2016 11:48:20 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
.vertx/debug-js/vertx-js/util/utils.js:23 TypeError: JSON.stringify got a cyclic data structure
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.objects.NativeJSON.JO(NativeJSON.java:278)
	at jdk.nashorn.internal.objects.NativeJSON.str(NativeJSON.java:268)
	at jdk.nashorn.internal.objects.NativeJSON.JO(NativeJSON.java:290)
	at jdk.nashorn.internal.objects.NativeJSON.str(NativeJSON.java:268)
	at jdk.nashorn.internal.objects.NativeJSON.JO(NativeJSON.java:290)
	at jdk.nashorn.internal.objects.NativeJSON.str(NativeJSON.java:268)
	at jdk.nashorn.internal.objects.NativeJSON.stringify(NativeJSON.java:196)
	at jdk.nashorn.internal.scripts.Script$Recompilation$562$1174A$\^eval\_#88\!17\^eval\_.L:1$convParamJsonObject(.vertx/debug-js/vertx-js/util/utils.js:23)
	at jdk.nashorn.internal.scripts.Script$Recompilation$561$1509A$\^eval\_#88\!17\^eval\_.L:1$convParamTypeUnknown(.vertx/debug-js/vertx-js/util/utils.js:40)
	at jdk.nashorn.internal.scripts.Script$Recompilation$560$2955A$\^eval\_#88\!17\^eval\_.L:1$Message$reply(.vertx/debug-js/vertx-js/message.js:107)
	at jdk.nashorn.internal.scripts.Script$Recompilation$559$1273A$\^eval\_#88\!17\^eval\_.L:1$authorise$callback(/home/luis/Documents/rethink/dev-msg-node-vertx/src/js/connector/policies/PoliciesConnector.js:32)
	at jdk.nashorn.internal.scripts.Script$Recompilation$534$1240AA$\^eval\_#88\!17\^eval\_.L:1$authorise(/home/luis/Documents/rethink/dev-msg-node-vertx/src/js/connector/policies/PoliciesConnector.js:35)
	at jdk.nashorn.internal.scripts.Script$Recompilation$531$1249A$\^eval\_#88\!17\^eval\_.L:1$L:30(/home/luis/Documents/rethink/dev-msg-node-vertx/src/js/connector/PoliciesConnectorVerticle.js:39)
	at jdk.nashorn.internal.scripts.Script$Recompilation$153$6349A$\^eval\_#88\!17\^eval\_.L:1$EventBus$consumer$L:134(.vertx/debug-js/vertx-js/event_bus.js:135)
	at io.vertx.core.Handler$$NashornJavaAdapter.handle(Unknown Source)
	at io.vertx.core.eventbus.impl.EventBusImpl$HandlerRegistration.handleMessage(EventBusImpl.java:1121)
	at io.vertx.core.eventbus.impl.EventBusImpl$HandlerRegistration.handle(EventBusImpl.java:1115)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$doReceive$179(EventBusImpl.java:755)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:335)
	at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$261(OrderedExecutorFactory.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by AnaSLCaldeira** [comment]
A pull request was issued to solve this error.
